openapi: "3.0.0"
info:
  version: 1.0.0
  title: Metabolite Index search page
  license:
    name: MIT
servers:
  - url: http://localhost:10050/api/v1
    description: tomcru dev server
paths:
  /metabolites/{mid}:
    get:
      summary: first attempt at getting metabolite
      operationId: getMetabolite
      x-lambda:
        lambda-id: metabolites/metabolite
#        role: asd
#        layers:
#          - asd
#          - esd
      x-integ:
        requestParameters:
          "query.mid": "path.mid"
      tags:
        - metabolites
      parameters:
        - name: mid
          in: path
          description: Metabolite primary ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Metabolite view
#          headers:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Metabolite"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Metabolite:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Metabolites:
      type: array
      items:
        $ref: "#/components/schemas/Metabolite"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
#  securitySchemes:
#    DoorsOIDC:
#      type: openIdConnect
#      openIdConnectUrl: http://localhost:5055/.well-known/openid-configuration
#      x-oidc:
#        audience:
#          - http://localhost:5000/
#        scopes:
#          - profile
